# This workflow will build and upload a node.js application when a commit is pushed to your default branch.
#

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install

    - name: Build App
      run: npm run build:linux
      env:
          GH_TOKEN: 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

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: build/*.AppImage
