# This workflow will build and upload a node.js application when a commit is pushed to your default branch.
#
name: Build Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install

    - name: Build Linux App
      run: npm run build:linux-arm

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: Linux-arm-app
        path: |
          build/*.AppImage
          build/*.exe
